In [2]:
import numpy as np

Задание 1

In [3]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

Задание 2

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [25]:
a_centered_sp = np.dot(a_centered[:5,:1].flatten(),a_centered[:5,1:2].flatten())
a_centered_sp = a_centered_sp/(len(a)-1)
a_centered_sp

2.0

Задание 4

In [28]:
m = np.cov(a.T)
m[0,1]

2.0